version: '3'

services:
  dev:
    image: node:12
    volumes:
      # before use: run docker volume create nodemodules
      # - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start
    ports:
      - 3000:3000

  # volumes:
  # nodemodules:
  #   external: true
